library(knitr)
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(maptools)
library(rmarkdown)
library(shiny)
library(shinyjs)
library(shinydashboard)
library(shinyFeedback)
library(shinyalert)
library(RPostgreSQL)
library(shinyBS)
library(dbplyr)
library(sodium)
library(DT)
library(lubridate)
library(scales)
library(RColorBrewer)
library(grid)

options(encoding = 'UTF-8')
header <- dashboardHeader( title = "COVID-19 BAZA OKUŽB", uiOutput("logoutbtn"))
sidebar <- dashboardSidebar(uiOutput("sidebarpanel")) 
body <- dashboardBody(shinyjs::useShinyjs(), uiOutput("body"))
ui<- dashboardPage(header, sidebar, body, skin = "blue")
